name: gruppe4
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

global_options:
  freezed:freezed:
    runs_before:
      - isar_generator:isar_generator

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  beamer: ^1.5.5
  cunning_document_scanner: ^1.1.2
  photo_view: ^0.14.0
  image_picker: ^0.8.8
  font_awesome_flutter: ^10.4.0
  social_share: ^2.3.1
  device_calendar: ^4.3.1
  share_plus: ^7.0.2
  flutter_carousel_widget: ^2.0.4
  timezone: ^0.9.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  isar_generator: ^3.1.0+1

flutter:
  assets:
    - assets/dev_debug_images/
  uses-material-design: true
